### ISSUE TITLE
Problem with running CH2OH-CO2_fit

### ISSUE THREAD

**Issue by Andrew-AbiMansour** [jaclark5/despasito#4]
## Command
```
python3 -m despasito -i despasito/examples/CH2OH-CO2_fit/input.json -p despasito/examples/CH2OH-CO2_fit
```

## Input JSON
```
{
    "beadconfig": [[0.5, [["CO2", 1]]],[0.5, [["CH3", 1], ["CH2OH", 1]]]],
    "SAFTgroup": "SAFTgroup.json",
    "SAFTcross": "SAFTcross.json",
    "association_site_names": ["H","e1","a1"],
    "opt_params": {
        "fit_bead" : "CH2OH",
        "fit_params": ["epsilon_CO2"],
        "epsilon_CO2_bounds" : [290.0, 310.0]
    },
    "CO2-ethanol": {
        "datatype": "TLVE",
        "calctype": "phase_xiT",
        "file": "CO2-ethanol_TLVE.csv"
    }        
}
```
## Output
```
$HOME/.local/lib/python3.7/site-packages/despasito/thermodynamics/calc.py:1705: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if ("yi_global" not in globals() or "True" in np.isnan(yi_global)):
Traceback (most recent call last):
  File "/home/levnon/.local/lib/python3.7/site-packages/despasito/fit_parameters/fit_funcs.py", line 147, in compute_SAFT_obj
    obj_function.append(data_obj.objective(eos))
  File "/home/levnon/.local/lib/python3.7/site-packages/despasito/fit_parameters/data_classes/TLVE.py", line 129, in objective
    phase_list, len_cluster = ff.reformat_ouput(phase_list)
  File "/home/levnon/.local/lib/python3.7/site-packages/despasito/fit_parameters/fit_funcs.py", line 26, in reformat_ouput
    type_cluster = [type(x) for x in cluster]
TypeError: 'NoneType' object is not iterable
```

**Comment by jaclark5** [comment]
I've was debugging and testing from my development branch and merged to the master branch without conflict, so I didn't test the master branch on my computer. At some point, we must have created a conflict because when I run this test it doesn't even get that far.

I temporarily uploaded my local version of the master branch as a new branch on GitHub called "master-local" and used the compare function here to confirm that it is identical.

I'm working on debugging it now

## Command
`python -m despasito -i despasito/examples/CH2OH-CO2_fit/input.json`

## Input
`{
    "beadconfig": [[0.5, [["CO2", 1]]],[0.5, [["CH3", 1], ["CH2OH", 1]]]],
    "SAFTgroup": "SAFTgroup.json",
    "SAFTcross": "SAFTcross.json",
    "association_site_names": ["H","e1","a1"],
    "opt_params": {
        "fit_bead" : "CH2OH",
        "fit_params": ["epsilon_CO2"],
        "epsilon_CO2_bounds" : [290.0, 310.0]
    },
    "CO2-ethanol": {
        "datatype": "TLVE",
        "calctype": "phase_xiT",
        "file": "CO2-ethanol_TLVE.csv"
    }        
}`

## Output
[INFO](root): Input args: Namespace(input='despasito/examples/CH2OH-CO2_fit/input.json', logFile='despasito.log', path='.', threads=1, verbose=0)
[INFO](despasito.main): Begin processing input file: despasito/examples/CH2OH-CO2_fit/input.json
Traceback (most recent call last):
  File "/anaconda3/envs/despasito/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/despasito/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Jennifer/bin/DESPASITO/despasito/despasito/__main__.py", line 61, in <module>
    run(**kwargs)
  File "/Users/Jennifer/bin/DESPASITO/despasito/despasito/main.py", line 25, in run
    eos_dict, thermo_dict = readwrite_input.extract_calc_data(filename, **args)
TypeError: extract_calc_data() got an unexpected keyword argument 'logFile'

**Comment by Andrew-AbiMansour** [comment]
That's a real possibility. Plz close this issue once you've fixed the problem.
